import { useCallback, useState } from "react";
import { motion } from "framer-motion";
import { Upload, Shield } from "lucide-react";

export default function ReportUpload({ onLoaded, onError }) {
  const [dragOver, setDragOver] = useState(false);

  const parseFile = useCallback(
    (file) => {
      if (!file) return;
      if (!file.name.endsWith(".json")) {
        onError("Please upload a .json file — the agent's report.json.");
        return;
      }
      const reader = new FileReader();
      reader.onload = () => {
        try {
          const data = JSON.parse(reader.result);
          if (!data.findings || !data.summary) {
            onError("Invalid audit report — missing 'findings' or 'summary' keys.");
            return;
          }
          onLoaded(data, file.name);
        } catch (e) {
          onError("Could not parse JSON: " + e.message);
        }
      };
      reader.readAsText(file);
    },
    [onLoaded, onError]
  );

  return (
    <div className="upload-state">
      <motion.div
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.2, ease: "easeOut" }}
        className={`upload-box ${dragOver ? "drag" : ""}`}
        onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragOver(false);
          parseFile(e.dataTransfer.files[0]);
        }}
      >
        <div className="upload-icon">
          <Shield size={24} strokeWidth={1.5} />
        </div>

        <h2 className="upload-title">Upload audit report</h2>
        <p className="upload-sub">
          Drop your <code>report.json</code> here, or click to browse.
          Generated by running <code>audit-agent</code> against your target.
        </p>

        <label className="btn-scan" style={{ cursor: "pointer", display: "inline-flex" }}>
          <Upload size={13} />
          Choose report.json
          <input
            type="file"
            accept=".json,application/json"
            hidden
            onChange={(e) => parseFile(e.target.files[0])}
          />
        </label>

        <div className="upload-hint">
          audit-agent --target &lt;host&gt; --transport docker
        </div>
      </motion.div>
    </div>
  );
}
