import { useCallback, useState } from "react";

export default function ReportUpload({ onLoaded, onError }) {
  const [dragOver, setDragOver] = useState(false);

  const parseFile = useCallback(
    (file) => {
      if (!file) return;
      if (!file.name.endsWith(".json")) {
        onError("Please upload a .json file — the agent's report.json.");
        return;
      }
      const reader = new FileReader();
      reader.onload = () => {
        try {
          const data = JSON.parse(reader.result);
          if (!data.findings || !data.summary) {
            onError(
              "This doesn't look like a valid audit report. Missing 'findings' or 'summary' keys."
            );
            return;
          }
          onLoaded(data, file.name);
        } catch (e) {
          onError("Could not parse JSON: " + e.message);
        }
      };
      reader.readAsText(file);
    },
    [onLoaded, onError]
  );

  return (
    <div className="upload-wrap">
      <div
        className={`upload-zone${dragOver ? " drag" : ""}`}
        onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragOver(false);
          parseFile(e.dataTransfer.files[0]);
        }}
      >
        <div className="upload-shield">🛡️</div>
        <h2>Drop your report here</h2>
        <p>or click to browse for <code>report.json</code></p>
        <p style={{ color: "var(--text-muted)", fontSize: "13px" }}>
          generated by <code>audit-agent</code>
        </p>

        <label className="btn btn-primary" style={{ marginTop: "24px", cursor: "pointer" }}>
          Choose report.json
          <input
            type="file"
            accept=".json,application/json"
            hidden
            onChange={(e) => parseFile(e.target.files[0])}
          />
        </label>

        <p className="upload-hint">
          audit-agent --target &lt;host&gt; --transport docker
        </p>
      </div>
    </div>
  );
}
